### ISSUE TITLE
Invalid argument (channelId): Invalid YouTube channel id.:

### ISSUE THREAD

**Issue by SimonPeter1909** [Hexer10/youtube_explode_dart#15] opened 2020-03-10 03:16 UTC
While using `getChannelUploads` I'm getting Invalid YouTube channel id for most of the channels. Please give me a solution. 
The Year, Month, Date of the `.uploadDate` of all videos fetched from `getChannelUploads` is 1975-01-08, but the time is correct.

**Comment by Hexer10** [comment] 2020-03-10 12:52
Could you post some ids that are not recognized as valid channel ids?

**Comment by Hexer10** [comment] 2020-03-10 12:54
I could reproduce the uploadDate issue

**Comment by SimonPeter1909** [comment] 2020-03-10 15:24
channel Id: UCr9Xq-j76QnRzCdTT9T8Ixw 

and the error - 

`Invalid argument (channelId): Invalid YouTube channel id.: "UCr9Xq-j76QnRzCdTT9T8Ixw"`

**Comment by SimonPeter1909** [comment] 2020-03-10 15:31
> Could you post some ids that are not recognized as valid channel ids?

channel Id: UCr9Xq-j76QnRzCdTT9T8Ixw

and the error -

Invalid argument (channelId): Invalid YouTube channel id.: "UCr9Xq-j76QnRzCdTT9T8Ixw"

**Comment by Hexer10** [comment] 2020-03-10 20:58
Thanks for the report, both issues should be fixed in the latest version (`0.0.13`)

**Closed** 2020-03-10 20:58 UTC
Labels: bug

**Comment by SimonPeter1909** [comment] 2020-03-11 01:42
Thank @Hexer10 The fix works perfectly. I need a feature. How to get channel id from a video? Right now the Video model got `video.author`, I need `video.channelId`. Thank You...

**Comment by Hexer10** [comment] 2020-03-11 11:07
> Thank @Hexer10 The fix works perfectly. I need a feature. How to get channel id from a video? Right now the Video model got `video.author`, I need `video.channelId`. Thank You...

I've added a new method: `getChannelIdFromVideo`, to retrieve the channel id from a video id, I could not add it to the `Video` model since it requires an additional api call.

Also, the next time you need a new feature create a new issue instead of adding more requests into an existing (closed) issue, thank you!
