### ISSUE TITLE
Playerlist response is broken.

### ISSUE THREAD

**Issue by emreesen27** [Hexer10/youtube_explode_dart#100] opened 2021-02-04 17:55 UTC
I'm searching using the method [here](https://github.com/Hexer10/youtube_explode_dart/issues/60). But the method doesn't work anymore. it returns the following message.

#### Unhandled Exception: TransientFailureException: Playerlist response is broken.

**Comment by in3mo** [comment] 2021-02-04 18:32
I have the same problem.

**Comment by YazeedAlKhalaf** [comment] 2021-02-04 19:28
yup seems youtube have changed something
we need to fix this asap

**Comment by YazeedAlKhalaf** [comment] 2021-02-04 19:47
`https://www.youtube.com/search_ajax?style=json&search_query=videos&page=1&hl=en` this is the current URL that is broken, we have to find the fix

**Comment by YazeedAlKhalaf** [comment] 2021-02-04 19:57
@in3mo @emreesen27 are you interested in trying to fix this problem? if you are add me on discord and we will start working on fixing it asap `YazeedAlKhalaf#8554`

**Comment by YazeedAlKhalaf** [comment] 2021-02-04 20:06
using this url redirects to youtube: `https://youtube.com/search?style=json&search_query=hello&page=0&hl=en`

**Comment by francigueco** [comment] 2021-02-05 11:58
Hi, I have the same problem, it would be nice if the problem is in the url that YouTube has modified, this url was an optional parameter of the getVideos method, so that the problem could be quickly solved in the app without having to wait for it the youtube_explode_dart package is updated.

I hope it can be solved soon, thank you!

**Comment by YazeedAlKhalaf** [comment] 2021-02-05 14:53
well I meant when you give the getVideos method a query, the URL used to get the data has been changed, we need to find the new one.

**Comment by zekkontro** [comment] 2021-02-08 19:00
I have a same error. Please solve this problem

**Comment by Andrei-Portales** [comment] 2021-02-11 05:12
have the same problem

**Comment by zekkontro** [comment] 2021-02-11 15:11
Please now you should hear our voices and solve this problem.

**Comment by kalismeras61** [comment] 2021-02-12 12:11
It is not working for the playlists anymore.

**Comment by YazeedAlKhalaf** [comment] 2021-02-12 12:13
Guys this library is a port of the original `C` one so why not join forces with the original guy and then when solved make a PR to this  port implementing the same fix. 
https://github.com/Tyrrrz/YoutubeExplode/issues/501

**Comment by Hexer10** [comment] 2021-02-12 16:03
I do not get paid or anything to work on this project so I try to work on this on my free time, and I don't have only this project going on other than my IRL job and school exams.
That being said I'm looking for a fix which is already being implementing the original library, when it has landed PR on this project are welcome!

**Comment by YazeedAlKhalaf** [comment] 2021-02-12 18:05
> I do not get paid or anything to work on this project so I try to work on this on my free time, and I don't have only this project going on other than my IRL job and school exams.
> That being said I'm looking for a fix which is already being implementing the original library, when it has landed PR on this project are welcome!

We really appreciate your work man 👍. Thanks for porting the code to Dart language.

**Comment by zekkontro** [comment] 2021-02-13 16:45
We appreciate your work.  Hexer 10 will you solve the problem or is this library over?

**Comment by Hexer10** [comment] 2021-02-13 16:51
It doesn't depend on me, I can't to much until the fix has landed on the original library, after then when I'll have time I can update this repo, (still if a PR is made this would accelerate the process)

**Comment by zekkontro** [comment] 2021-02-13 20:40
Ok. Thank you very much @Hexer10 !

**Comment by kalismeras61** [comment] 2021-02-16 19:15
@Hexer10  PR iscreated for main repo.  Can you check it ?  We appreciate your work.
https://github.com/Tyrrrz/YoutubeExplode/pull/502/files

**Comment by Hexer10** [comment] 2021-02-26 14:13
The PR has been merged and now we can start implementing the fixes here, unfortunately lately I don't have much time tough I'll try to get something working, if someone wants to make a PR implementing the fixes it would be really appreciated

**Comment by Hexer10** [comment] 2021-02-26 15:21
I've already release the version `1.8.0-beta.0` which should address the search issue, please check  the changelog and the updates unit test to understand how it works.
This is a breaking changes but should be easy enough to fix, some info about the videos might be not detailed as before.

Please comment here if are still having issues searching content. (`SearchList` is exactly like a `List` you can loop ad access elements with `[]` and has a `nextPage()`, to indeed get the batch of videos.)

**Comment by zekkontro** [comment] 2021-02-26 19:08
Is the problem solved?

**Comment by Hexer10** [comment] 2021-02-26 19:30
> Is the problem solved?

As I've said the searching issue is fixed, the playlist part is still broken tough

**Comment by zekkontro** [comment] 2021-02-26 20:05
As far as I understand you have created a class named searchList and searchVideo each. Can't import the entire Video class into SearchVideo? It would be nice if there was only one class just like before

**Comment by Hexer10** [comment] 2021-02-26 20:39
> As far as I understand you have created a class named searchList and searchVideo each. Can't import the entire Video class into SearchVideo? It would be nice if there was only one class just like before

So, I could do that, but right now the classes are different since searching a video now doesn't get the likes and dislikes while the video class holds those values in `engagement`

Note: I just release 1.8.0-beta.1 to export properly the `SearchList`

**Comment by zekkontro** [comment] 2021-02-26 20:49
Ok, Thank you very much for considering my suggestion :)

**Comment by Hexer10** [comment] 2021-02-27 18:01
Just release a new version that does exactly that, now `SearchList`  contains only elements of `Video` (and not `SearchVideo`), note that some values are null.

When the nnbd update will come I plan to address better this issue but right now I'm focusing on fixing the most severe bugs.

**Comment by kalismeras61** [comment] 2021-02-27 18:31
@Hexer10 do you have any plan for playlists ?

**Comment by zekkontro** [comment] 2021-02-27 19:02
@Hexer10  search works very well. I guess only the playlists are left now. I think it would be nice if a class like SearchList returns in playlists.

**Comment by lrorpilla** [comment] 2021-02-28 17:15
I'm also in a critical need of fixes for playlists for an app I'm making. Search works wonders for me in the meantime, this package is really a relief now I wouldn't have to deal with the API limits.

Not sure but I think some keywords stuff up the search and refuse to query. I'll see if I can run into and reproduce the problem again.

**Comment by zekkontro** [comment] 2021-02-28 17:18
Has the playlist problem been solved in the main project?

**Comment by Hexer10** [comment] 2021-02-28 18:31
Not yet, tomorrow I should have some time to works on this

**Comment by lrorpilla** [comment] 2021-03-01 10:27
Regarding search, on occasion I seem to be unable to query any search results if I tried searching with a known username. This is strange and I'm not sure if this is a problem on my end, I'm just using the search function -- but I'm unable to get results if I searched something with say, a renowned channel name.

**Comment by Hexer10** [comment] 2021-03-04 09:48
Just published version `1.8.0-beta.3` which should address _most_ of the playlist issues, please try it out, let me know if you find any issue.

The syntax has not been changed from v1.7 .

**Comment by zekkontro** [comment] 2021-03-04 09:56
Congratulations!! The error appears to be resolved How can I convert the List <Video> class to a SearchList class? I have one stf widget, but it accepts the SearchList class. I want to solve it in one page instead of creating 2 different pages

**Comment by Hexer10** [comment] 2021-03-04 09:59
> Congratulations!! The error appears to be resolved How can I convert the List

`.getVideos` returns a stream if you want a list of all the videos you can use `.getVideos(..).toList()`



> Regarding search, on occasion I seem to be unable to query any search results if I tried searching with a known username. This is strange and I'm not sure if this is a problem on my end, I'm just using the search function -- but I'm unable to get results if I searched something with say, a renowned channel name.
> 
> Some example search terms that would result to a null for me: "linustechtips", "pewdiepie", "tom scott". Chances are if I use the YouTube app to search a term and a channel shows up in a search, that search query wouldn't work.

There was an issue when a search return a stream video, just fixed in `1.8.0-beta.5`

**Comment by zekkontro** [comment] 2021-03-04 10:01
How can I convert the` List <Video>` class to a `SearchList` class? I have one stf widget, but it accepts the SearchList class. I want to solve it in one page instead of creating 2 different pages

**Comment by Hexer10** [comment] 2021-03-04 10:02
> How can I convert the` List <Video>` class to a `SearchList` class? I have one stf widget, but it accepts the SearchList class. I want to solve it in one page instead of creating 2 different pages

Are you using the `nextPage` method of `SearchList` ? if not it would be just better to call `SearchList.toList()` and use two `List<Video>`

**Comment by zekkontro** [comment] 2021-03-04 10:07
> > ` List <Video>`Sınıfı bir `SearchList`sınıfa nasıl dönüştürebilirim ? Bir stf widget'ım var, ancak SearchList sınıfını kabul ediyor. 2 farklı sayfa oluşturmak yerine tek sayfada çözmek istiyorum
> 
> `nextPage`Yöntemini kullanıyor musunuz `SearchList`? değilse, sadece `SearchList.toList()`ikisini aramak ve kullanmak daha iyi olur `List<Video>`.
> 
> `SearchList`Gerekirse oynatma listesinden almak için bir API eklemeyi düşünebilirim.

I don't using the `nextPage `method. I did not understand your solution suggestion, but a novelty might be good for this

**Comment by Hexer10** [comment] 2021-03-04 10:12
You can call the .toList method on the SearchList class so both methods returns `List<Video>` eg
```
yt.search.getVideos(...).toList();
```

**Comment by zekkontro** [comment] 2021-03-04 10:17
Everything works great mate thank you very much!!

**Comment by lrorpilla** [comment] 2021-03-04 12:29
Thank you so much for your work, playlists and search getting fixed are vital for a new feature on my app, much appreciated

**Comment by Hexer10** [comment] 2021-03-10 18:16
This should be now fixed, I published `1.8.0` stable version

Feel free to open a new issue if you find any problem!

**Closed by Hexer10** 2021-03-10 18:16 UTC
Labels: bug, help wanted
