### ISSUE TITLE
XMLHttpRequest error [BUG]

### ISSUE THREAD

**Issue by mrhmamun** [Hexer10/youtube_explode_dart#128] opened 2021-05-28 10:34 UTC
I am trying to get yt metadata but it's showing  XMLHttpRequest error on Flutter Web. 

Here's my code: 

  void _fetchMetadata(String link) async {
    try {
      // metaData = await YoutubeMetaData.getData(link);
      var yt = YoutubeExplode();
      var video = await yt.videos.get(link);

      setState(() {
        _title = video.title;
        _desc = video.description;
        _thumbImage = video.thumbnails.toString();
        _duration = video.duration.toString();
      });

      print('Title: ${video.title}');
      print(video.title);
      print(video.thumbnails);
      print(video.description);
    } catch (e) {
      print(e);
      // metaData = null;
    }
    setState(() {});
  }

flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.2.0, on Mac OS X 10.15.1 19B88 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.9.1 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[!] Android Studio
    ✗ Android Studio not found at /path/to/android/studio/Contents
[✓] VS Code (version 1.55.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.

**Comment by Hexer10** [comment] 2021-05-28 12:05
Dupe of https://github.com/Hexer10/youtube_explode_dart/issues/119 

Unfortunately making this work in web is not really straight forward

**Closed by Hexer10** 2021-05-28 12:05 UTC
Labels: bug
