### ISSUE TITLE
[BUG] FormatException

### ISSUE THREAD

**Issue by Artx-II** [Hexer10/youtube_explode_dart#90] opened 2020-12-02 21:05 UTC
**Describe the bug**
On some videos, getManifest will throw FormatException

**To Reproduce**
```dart
test('VideoId - _H0-dOAjXBk', () async {
    var manifest = await yt.videos.streamsClient
      .getManifest(VideoId('_H0-dOAjXBk'));
    for (var streamInfo in manifest.streams) {
      expect(yt.videos.streamsClient.get(streamInfo), emits(isNotNull));
    }
  });
```

**Stacktrace**
FormatException: Unexpected character (at character 2)
{args:{raw_player_response:ytInitialPlayerResponse}}
 ^

**Enviroment: (please complete the following information):**
 - Enviroment: Dart VM (Happens on Flutter 1.22.4 too)
 - Version 2.10.4 (Dart SDK)
 - YoutubeExplode Version ^1.7.3

**Additional context**
Link for the Video: https://www.youtube.com/watch?v=_H0-dOAjXBk

**Comment by Hexer10** [comment] 2020-12-06 11:09
Unfortunately I'm not able to reproduce this, does it still happen?

**Comment by Artx-II** [comment] 2020-12-06 22:05
I made someone else test if the video worked and it did, then I tried with a VPN and it worked for me too, I think the issue has something to do with my Internet provider but what is really weird is that even though it doesn't work for me with without a VPN, I can normally watch that video on Youtube.

Do you have any idea of why does that happen? I you don't feel free to close the issue, this is literally the only video that doesn't work for me.

**Comment by Hexer10** [comment] 2020-12-25 22:30
Please try again with the latest version, now it should be fixed, reopen if this still happens

**Closed** 2020-12-25 22:38 UTC
Labels: bug, question
