### ISSUE TITLE
The app has been rejected from the AppStore.

### ISSUE THREAD

**Issue by jtaxiexpress** [Hexer10/youtube_explode_dart#230] opened 2022-12-10 03:33 UTC
```
Guideline 5.2.3 - Legal

Since your app streams contents from YouTube, we still require documentary evidence from YouTube that shows you have all necessary rights or permissions to the third-party video streaming in your app.

Documentary evidence can be terms of use or copyright/permissions statement that has been officially published by YouTube.
```

What about your apps?
How are you dealing with it?

**Comment by RamiroGarrido** [comment] 2022-12-12 22:37
This library is a work around to gain access to the youtube api...but the LEGAL way to do this is registering yourself inside the google cloud console and activating the youtube api through it, so u can access the api with your own api key. That way google is able track your usage of their api and charge u if u pass the limit rates. I guess this is the first time you use a google api friend...all their apis are managed through the google cloud console.

**Comment by Hexer10** [comment] 2022-12-20 13:59
Dupe of https://github.com/Hexer10/youtube_explode_dart/issues/152

Unfortunately I've no suggestions on how to deal this.

**Closed by Hexer10** 2022-12-20 13:59 UTC
Labels: enhancement
