### ISSUE TITLE
[BUG] channels.getUploadsFromPage(...) crash

### ISSUE THREAD

**Issue by nocode-nomoney** [Hexer10/youtube_explode_dart#105] opened 2021-02-21 10:41 UTC
After excuting 'yt.channels.getUploadsFromPage(...)'.
it gets first 30 videos, then while attempting to access nextContinuationData, it crashes because it is null.
I think YouTube changed there json sturucture.
I checked the page source and found out that there's informatnion about Continuation
It might help you to find solution..

it shows continuation == null
=======
==richGridRenderer:{contents:[],continuations:[{nextContinuationData:{continuation:""}}]}}}}]}}}},
=======
and I assume this is maybe the information about continuation
=====
==continuationItemRenderer":{"trigger":"CONTINUATION_TRIGGER_ON_ITEM_SHOWN","continuationEndpoint":{"clickTrackingParams":"CDYQ6IsCGAAiEwiassnz3vruAhURU3wKHSztD5g=","commandMetadata":{"webCommandMetadata":{"sendPost":true,"apiUrl":"/youtubei/v1/browse"}},"continuationCommand":{"token":"4qmFsgJ_EhhVQ0dEQTFlNnFRU0FIMFI5aG9pcDlWckEaNEVnWjJhV1JsYjNNWUF5QUFNQUU0QWVvREZFTm5RVk5EZDJwRWFEZFVUbk5pWHkxbkxUQkOaAixicm93c2UtZmVlZFVDR0RBMWU2cVFTQUgwUjlob2lwOVZyQXZpZGVvczEwMg%3D%3D","request":"CONTINUATION_REQUEST_TYPE_BROWSE"}}}}],"trackingParams":"CDYQ6IsCGAAiEwiassnz3vruAhURU3wKHSztD5g=","targetId":"browse-

**Comment by Hexer10** [comment] 2021-03-01 09:14
Dupe of  #100 , I'm already working on this.

**Closed by Hexer10** 2021-03-01 09:14 UTC
Labels: bug
