### ISSUE TITLE
[BUG] Cors Error when running on flutter_web?

### ISSUE THREAD

**Issue by corcomm** [Hexer10/youtube_explode_dart#129] opened 2021-06-15 14:28 UTC
Has anyone used youtbue_explode_dart in flutter_web.
Works on android emulator.  But the same code running flutter_web from android studio gives error.

Access to XMLHttpRequest at 'https://youtube.com/get_video_info?video_id=2HmbNYpmxab&el=embedded&eurl=https://youtube.googleapis.com/v/2HmbNYpmxab&hl=en&html5=1' from origin 'http://localhost:4914' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Is there any additional steps need to be taken to run the same codebase on flutter_web?

**Comment by korcomm** [comment] 2021-06-15 14:35
This is more complete list of errors from Chrome Developer Tools Console window:
(Note video url has been changed for privacy reasons.)

linked_hash_map.dart:21 Refused to set unsafe header "user-agent"
linked_hash_map.dart:21 Refused to set unsafe header "cookie"
linked_hash_map.dart:21 Refused to set unsafe header "sec-fetch-dest"
linked_hash_map.dart:21 Refused to set unsafe header "sec-fetch-mode"
linked_hash_map.dart:21 Refused to set unsafe header "sec-fetch-site"
linked_hash_map.dart:21 Refused to set unsafe header "sec-fetch-user"
linked_hash_map.dart:21 Refused to set unsafe header "sec-gpc"
:8429/#/:1 Access to XMLHttpRequest at 'https://youtube.com/get_video_info?video_id=2HmbNYpmxab&el=embedded&eurl=https://youtube.googleapis.com/v/2HmbNYpmxab&hl=en&html5=1' from origin 'http://localhost:8429' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by Hexer10** [comment] 2021-06-16 11:30
Dupe of https://github.com/Hexer10/youtube_explode_dart/issues/119

Unfortunately this cannot be fixed

**Closed by Hexer10** 2021-06-16 11:30 UTC
Labels: bug
