### ISSUE TITLE
[BUG] Youtube Remove video_info endpoint, 

### ISSUE THREAD

**Issue by dariuspo** [Hexer10/youtube_explode_dart#145] opened 2021-07-22 02:58 UTC
Looks like the video_info end point is removed:

Related Youtube Explode C# Repository:
https://github.com/Tyrrrz/YoutubeExplode/issues/565

![image](https://user-images.githubusercontent.com/58877825/126584134-48771511-672b-44b0-9e27-56ea21cb2e56.png)

**Comment by Hexer10** [comment] 2021-07-22 12:44
Dupe of #144

**Closed by Hexer10** 2021-07-22 12:44 UTC
Labels: bug
